controllers:
    resource: ../src/Controller/
    type: attribute


app_home:
    path: /
    controller: App\Controller\FizzBuzz\FizzBuzz::index

app_fizzbuzz:
    path: /desafio/fizz/buzz
    controller: App\Controller\FizzBuzz\FizzBuzz::fizzBuzz